/**
 * Measure romaji/kana coverage of the address dataset, per prefecture.
 *
 * Why this exists: the whole library rests on the dataset actually carrying
 * readings for town names. Where it does not, `toRomaji` must refuse. This
 * script quantifies exactly how often that happens, so the README can state
 * real numbers instead of an assurance.
 *
 * Run it against a generated dataset:
 *
 *   pnpm --filter jp-address-romaji-data build:data -- --out ./address-data
 *   pnpm coverage:measure -- --data ./address-data > docs/coverage.md
 *
 * The output is Markdown, intended to be committed as docs/coverage.md.
 */

import fs from 'node:fs';
import path from 'node:path';

interface City {
  county?: string;
  city: string;
  ward?: string;
}
interface Pref {
  pref: string;
  cities: City[];
}
interface Town {
  oaza_cho?: string;
  oaza_cho_k?: string;
  oaza_cho_r?: string;
  chome_n?: number;
}

interface Bucket {
  total: number;
  withRomaji: number;
  withKana: number;
  usable: number;
  chomeTotal: number;
  chomeUsable: number;
  oazaPrefixed: number;
  oazaPrefixedUsable: number;
}

function emptyBucket(): Bucket {
  return {
    total: 0, withRomaji: 0, withKana: 0, usable: 0,
    chomeTotal: 0, chomeUsable: 0, oazaPrefixed: 0, oazaPrefixedUsable: 0,
  };
}

/** Same rule the library uses: a name that is only digits is corrupt data. */
function isUsable(value: string | undefined): boolean {
  if (!value) return false;
  const stem = value.replace(/[\s-]*\d+$/, '').trim();
  return stem.length > 0 && /[A-Za-z]/.test(stem);
}

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1]! : fallback;
}

function pct(numerator: number, denominator: number): string {
  return denominator === 0 ? '—' : `${((numerator / denominator) * 100).toFixed(2)}%`;
}

function main(): void {
  const dataDir = path.resolve(arg('data', './address-data'));
  const indexPath = path.join(dataDir, 'ja.json');
  if (!fs.existsSync(indexPath)) {
    console.error(`No dataset at ${indexPath}. Generate one first:`);
    console.error('  pnpm --filter jp-address-romaji-data build:data -- --out ./address-data');
    process.exit(1);
  }

  const index = JSON.parse(fs.readFileSync(indexPath, 'utf-8')) as { data: Pref[] };
  const byPref = new Map<string, Bucket>();
  const national = emptyBucket();
  let missingFiles = 0;

  for (const pref of index.data) {
    const bucket = byPref.get(pref.pref) ?? emptyBucket();
    byPref.set(pref.pref, bucket);

    for (const city of pref.cities) {
      const municipality = `${city.county ?? ''}${city.city}${city.ward ?? ''}`;
      const file = path.join(dataDir, 'ja', pref.pref, `${municipality}.json`);
      if (!fs.existsSync(file)) {
        missingFiles++;
        continue;
      }
      const towns = (JSON.parse(fs.readFileSync(file, 'utf-8')) as { data: Town[] }).data;

      for (const town of towns) {
        if (!town.oaza_cho) continue;
        const usable = isUsable(town.oaza_cho_r) || Boolean(town.oaza_cho_k);
        for (const b of [bucket, national]) {
          b.total++;
          if (town.oaza_cho_r) b.withRomaji++;
          if (town.oaza_cho_k) b.withKana++;
          if (usable) b.usable++;
          if (town.chome_n !== undefined) {
            b.chomeTotal++;
            if (usable) b.chomeUsable++;
          }
          if (town.oaza_cho.startsWith('大字')) {
            b.oazaPrefixed++;
            if (usable) b.oazaPrefixedUsable++;
          }
        }
      }
    }
  }

  const rows = [...byPref.entries()]
    .filter(([, b]) => b.total > 0)
    .sort((a, b) => a[1].usable / a[1].total - b[1].usable / b[1].total);

  const out: string[] = [];
  out.push('# Romanization coverage');
  out.push('');
  // Deliberately not the absolute path: this file is committed, and embedding
  // a CI runner's working directory makes every regeneration look like a diff.
  out.push('Generated by `scripts/measure-coverage.ts`. Regenerate with:');
  out.push('');
  out.push('```sh');
  out.push('npx tsx packages/data/src/build-data.ts --out ./address-data');
  out.push('npx tsx scripts/measure-coverage.ts --data ./address-data > docs/coverage.md');
  out.push('```');
  out.push('');
  out.push('A town is counted as **usable** when the dataset carries either a valid romaji');
  out.push('field or a kana reading. Entries whose romaji collapsed to a bare number are');
  out.push('counted as unusable, matching what the library does at runtime.');
  out.push('');
  out.push('## National');
  out.push('');
  out.push(`| Metric | Count | Share |`);
  out.push(`| --- | ---: | ---: |`);
  out.push(`| Town entries | ${national.total} | 100% |`);
  out.push(`| With a romaji field | ${national.withRomaji} | ${pct(national.withRomaji, national.total)} |`);
  out.push(`| With a kana reading | ${national.withKana} | ${pct(national.withKana, national.total)} |`);
  out.push(`| **Usable** | ${national.usable} | ${pct(national.usable, national.total)} |`);
  out.push(`| Chome entries (urban) | ${national.chomeTotal} | ${pct(national.chomeUsable, national.chomeTotal)} usable |`);
  out.push(`| \`大字\`-prefixed (rural) | ${national.oazaPrefixed} | ${pct(national.oazaPrefixedUsable, national.oazaPrefixed)} usable |`);
  out.push('');
  out.push('## By prefecture');
  out.push('');
  out.push('Sorted by overall coverage, lowest first.');
  out.push('');
  out.push('| Prefecture | Towns | Usable | Chome entries | Chome usable |');
  out.push('| --- | ---: | ---: | ---: | ---: |');
  for (const [pref, b] of rows) {
    out.push(
      `| ${pref} | ${b.total} | ${pct(b.usable, b.total)} | ${b.chomeTotal} | ${pct(b.chomeUsable, b.chomeTotal)} |`,
    );
  }

  if (missingFiles > 0) {
    out.push('');
    out.push(`> ⚠️ ${missingFiles} municipality files were missing from the dataset;`);
    out.push('> these numbers are incomplete. Re-run the data build.');
  }

  console.log(out.join('\n'));
}

main();
